bases:
  - ../../base
  
patches:
  - target:
      kind: Deployment
      name: java-app
    patch: |-
        - op: replace
          path: /spec/replicas
          value: 1
  - target:
      kind: Service
      name: java-app-service
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30001

configMapGenerator:
  - name: app-config
    namespace: dev-ns
    literals:
      - APP_ENV=development
      - WELCOME_MESSAGE=Bienvenido al Ambiente de Desarrollo
      - VERSION=1.0.0-dev
      - API_URL=http://dev-api.example.com
      - APP_COLOR=lightgreen
    options:
      disableNameSuffixHash: true

images:
  - name: rhxpchispi/zlab-java-app
    newTag: dev-latest

namespace: dev-ns