bases:
  - ../../base
  
patches:
  - target:
      kind: Deployment
      name: java-app
    patch: |-
        - op: replace
          path: /spec/replicas
          value: 1
  - target:
      kind: Service
      name: java-app-service
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30003

configMapGenerator:
  - name: app-config
    namespace: dev-ns
    literals:
      - APP_ENV=production
      - WELCOME_MESSAGE=Bienvenido al Ambiente de Producción
      - VERSION=1.0.0
      - API_URL=http://api.example.com
      - APP_COLOR=lightcoral
    options:
      disableNameSuffixHash: true

images:
  - name: rhxpchispi/zlab-java-app
    newTag: prod-latest

namespace: prod-ns