apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    name: http
    nodePort: 30001
